-- Paper Bot Lab: named, freely-configurable paper bots.
--
-- Prisma is the single source of schema truth; this migration is hand-authored
-- because it interleaves a data backfill between an additive column and a
-- constraint change: add is_comparison -> backfill existing rows as the canonical
-- comparison bots and name them -> drop the one-per-(campaign, portfolio) unique
-- and replace it with a comparison-only partial unique. The autogenerated
-- migration cannot express the interleaved backfill.
--
-- A "bot" IS a PaperCampaign row. The three existing baseline/simulation/hybrid
-- portfolios become the canonical COMPARISON bots (is_comparison = true), keeping
-- Model Performance's 3-way comparison intact; custom bots created via the Lab are
-- is_comparison = false. Many bots may share an engine, so the old unique on
-- (evaluation_campaign_id, portfolio) is dropped; a partial unique index keeps the
-- comparison bots singular per portfolio.

-- Step 1 (additive): the discriminator lands with a default so existing rows are
-- valid immediately; the backfill below flips them to true.
ALTER TABLE "paper_campaigns"
    ADD COLUMN "is_comparison" BOOLEAN NOT NULL DEFAULT false;

-- Step 2 (backfill): every pre-existing paper_campaign is a canonical comparison
-- bot. Name any unnamed one by its engine so the Lab list has a human label. A
-- row that already carries an operator label keeps it.
UPDATE "paper_campaigns" SET "is_comparison" = true;

UPDATE "paper_campaigns"
    SET "label" = 'Baseline'
    WHERE "label" IS NULL AND "portfolio" = 'baseline';
UPDATE "paper_campaigns"
    SET "label" = 'Simulation'
    WHERE "label" IS NULL AND "portfolio" = 'simulation';
UPDATE "paper_campaigns"
    SET "label" = 'Hybrid'
    WHERE "label" IS NULL AND "portfolio" = 'hybrid';

-- Step 3 (constraint change): drop the one-per-(campaign, portfolio) unique so a
-- Lab bot may share an engine with the comparison bots and with other Lab bots.
DROP INDEX "paper_campaigns_evaluation_campaign_id_portfolio_key";

-- The three canonical comparison bots remain singular per portfolio: at most one
-- comparison bot of each engine per evaluation campaign. Custom bots (false) are
-- excluded from the constraint, so any number of them may share an engine. Prisma
-- cannot express a partial unique index, so it lives here.
CREATE UNIQUE INDEX "paper_campaigns_comparison_portfolio_uniq"
    ON "paper_campaigns" ("evaluation_campaign_id", "portfolio")
    WHERE "is_comparison";

-- The Lab list and the cycle enumerate bots by (campaign, is_comparison).
CREATE INDEX "paper_campaigns_evaluation_campaign_id_is_comparison_idx"
    ON "paper_campaigns" ("evaluation_campaign_id", "is_comparison");
